version: "3.9"

networks:
    default:
        external:
            name: ${NETWORK_NAME}

volumes:
    vendor:
        external:
            name: ${PROJECT_NAME}_vendor
    database:
        external:
            name: ${PROJECT_NAME}_database

services:
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        restart: always
        depends_on:
            - php
        image: ${COMPANY_NAME}/${PROJECT_NAME}-nginx-dev
        build:
            context: ../
            dockerfile: docker/nginx/dev/Dockerfile
        ports:
            - ${PUBLIC_PORT}:80
        volumes:
            - ../public:/var/www/public
        networks:
            default:
                aliases:
                    - nginx
#                    - ${VIRTUAL_HOST}

    php:
        container_name: ${PROJECT_NAME}_php
        restart: always
        depends_on:
            - mysql
        image: ${COMPANY_NAME}/${PROJECT_NAME}-php-dev
        build:
            context: ../
            dockerfile: docker/php/dev/Dockerfile
        env_file:
            - ../.env.local
        volumes:
            - ../bin:/var/www/bin
            - ../config:/var/www/config
            - ../migrations:/var/www/migrations
            - ../public:/var/www/public
            - ../src:/var/www/src
            - ../templates:/var/www/templates
            - ../tests:/var/www/tests
            - ../translations:/var/www/translations
            - ../var:/var/www/var
            - ../vendor:/var/www/vendor
            - ../.env:/var/www/.env
            - ../composer.json:/var/www/composer.json
            - ../composer.lock:/var/www/composer.lock
            - ../phpunit.xml.dist:/var/www/phpunit.xml.dist
            - ../symfony.lock:/var/www/symfony.lock
        networks:
            default:
                aliases:
                    - php

    mysql:
        container_name: ${PROJECT_NAME}_mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - 3310:3306
        volumes:
            - database:/var/lib/mysql
        networks:
            default:
                aliases:
                    - mysql
