version: "3.9"

networks:
    default:
        external:
            name: ${NETWORK_NAME}

volumes:
    vendor:
        external:
            name: ${PROJECT_NAME}_vendor
    bundles:
        external:
            name: ${PROJECT_NAME}_bundles
    database:
        external:
            name: ${PROJECT_NAME}_database

services:
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        restart: always
        depends_on:
            - php
        image: ${COMPANY_NAME}/${PROJECT_NAME}-nginx-prod
        build:
            context: ../
            dockerfile: docker/nginx/prod/Dockerfile
        ports:
            - ${PUBLIC_PORT}:80
        volumes:
            - bundles:/var/www/public/bundles
        #cpus: 0.1
        #mem_limit: 64M
        logging:
            driver: "json-file"
            options: { max-size: "10m", max-file: "3" }
        networks:
            default:
                aliases:
                    - nginx

    php:
        container_name: ${PROJECT_NAME}_php
        restart: always
        depends_on:
            - mysql
        image: ${COMPANY_NAME}/${PROJECT_NAME}-php-prod
        build:
            context: ../
            dockerfile: docker/php/prod/Dockerfile
        env_file:
            - ../.env.local
        volumes:
            - bundles:/var/www/public/bundles
            - vendor:/var/www/vendor
        #cpus: 0.1
        #mem_limit: 64M
        logging:
            driver: "json-file"
            options: { max-size: "10m", max-file: "3" }
        networks:
            default:
                aliases:
                    - php

    cron:
        container_name: ${PROJECT_NAME}_cron
        restart: always
        depends_on:
            - mysql
        image: ${COMPANY_NAME}/${PROJECT_NAME}-php-prod
        build:
            context: .
            dockerfile: docker/php/prod/Dockerfile
        env_file: ../.env.local
        volumes:
            - bundles:/var/www/public/bundles
            - vendor:/var/www/vendor
        #cpus: 0.1
        #mem_limit: 64M
        entrypoint: /cron-entry.sh
        command: /cron-cmd.sh
        logging:
            driver: "json-file"
            options: { max-size: "2m", max-file: "3" }
        networks:
            default:
                aliases:
                    - cron

    mysql:
        container_name: ${PROJECT_NAME}_mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - database:/var/lib/mysql
        networks:
            default:
                aliases:
                    - mysql
